FROM python:3.8

RUN mkdir -p /home/src/app
ADD requirements.txt /home/src/app
RUN pip install -r /home/src/app/requirements.txt
ADD backend.py /home/src/app
ADD /backend /home/src/app/backend
ADD exec.sh /home/src/app
RUN chmod +x /home/src/app/exec.sh

CMD "/home/src/app/exec.sh"
