version: "3.9"
networks:
  bot-network:
    name: bot-network
services:
  bot-db:
    image: postgres
    networks:
      - bot-network
    environment:
      POSTGRES_DB: illuminatenorden
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  nginx:
    image: rariramz/nginx
    networks:
      - bot-network
    ports:
      - "5000:3865"
  backend:
    image: rariramz/backend
    networks:
      - bot-network
    environment:
      FLASK_APP: /home/src/app/backend/__init__.py
  app:
    image: rariramz/app
    networks:
      - bot-network
    environment:
      telegram_bot_token: "1840899044:AAF-X6uFxN6oyzFghj0Ub9YXDeuB-vgxWLM"
      bot_url: "https://f737d35910a1.ngrok.io"
      backend_url: "http://backend:8000"
