FROM python:3.8

RUN mkdir -p /home/src/app
ADD requirements.txt /home/src/app
RUN pip install -r /home/src/app/requirements.txt
ADD main.py /home/src/app
ADD /app /home/src/app/app

CMD ["python3", "-u", "/home/src/app/main.py"]
